import requests
import speech_recognition as sr
import pygame
import os
import time

# Configuration
BOT_URL = "http://localhost:5005/webhooks/my_voice_channel/webhook"
SENDER_ID = "nithish_voice_user"

def play_audio(file_path):
    """Plays the MP3 file generated by the bot."""
    try:
        pygame.mixer.init()
        pygame.mixer.music.load(file_path)
        pygame.mixer.music.play()
        
        # Wait until audio finishes
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
            
        # Unload so we can delete or overwrite it later
        pygame.mixer.music.unload()
        # Small delay to release file lock
        time.sleep(0.5)
        
    except Exception as e:
        print(f"❌ Error playing audio: {e}")

def listen_to_user():
    """Listens to the microphone and returns text."""
    r = sr.Recognizer()
    
    # NEW SETTINGS: Make it less sensitive to silence
    r.energy_threshold = 4000  # distinct speech level
    r.dynamic_energy_threshold = True
    r.pause_threshold = 1.2    # Wait 1.2 seconds of silence before thinking you are done

    with sr.Microphone() as source:
        print("\n🎤 Listening... (Speak now!)")
        
        # Reduced calibration time to make it snappier
        r.adjust_for_ambient_noise(source, duration=0.5)
        
        try:
            # Increased phrase_time_limit to 15 seconds so you can speak longer sentences
            audio = r.listen(source, timeout=5, phrase_time_limit=15)
            
            print("⏳ Processing speech...")
            text = r.recognize_google(audio)
            print(f"🗣️ You said: '{text}'")
            return text
            
        except sr.WaitTimeoutError:
            return None # Just ignore silence loop
        except sr.UnknownValueError:
            print("⚠️ (Audio unclear)") # Cleaner log
            return None
        except sr.RequestError:
            print("❌ Google Speech API Error.")
            return None

def main():
    print("--- 🤖 VOICE ADVISOR CLI ---")
    print("Press Ctrl+C to exit.")
    
    while True:
        # 1. Get Voice Input
        user_text = listen_to_user()
        
        if user_text:
            # 2. Send to Rasa Bot
            print("📤 Sending to bot...")
            try:
                payload = {"sender": SENDER_ID, "text": user_text}
                r = requests.post(BOT_URL, json=payload)
                
                if r.status_code == 200:
                    response_data = r.json()
                    bot_text = response_data.get("bot_text_response", "")
                    
                    print(f"🤖 Bot says: {bot_text}")
                    
                    # 3. Play Bot Audio
                    # The connector saves the file as 'bot_reply.mp3' in the project root
                    audio_path = "bot_reply.mp3"
                    if os.path.exists(audio_path):
                        play_audio(audio_path)
                    else:
                        print("⚠️ No audio file found to play.")
                else:
                    print(f"❌ Server Error: {r.status_code}")
                    
            except Exception as e:
                print(f"❌ Connection Error: {e}")
                print("   (Make sure 'python final_launch.py' is running in another window!)")

if __name__ == "__main__":
    main()